# Generated by Django 4.1.7 on 2023-04-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_ingredient_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DownloadShoppingCart',
            new_name='RecipeIngredient',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='img_recipe', verbose_name='Загрузить фото'),
        ),
    ]
