# Generated by Django 4.1.7 on 2023-05-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'pizza', 'verbose_name_plural': 'stories'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'pizza', 'verbose_name_plural': 'stories'},
        ),
    ]
